package com.peopleos.activity.entity;

public enum ActivityType {
    EMPLOYEE_ADDED,
    EMPLOYEE_UPDATED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    ATTENDANCE_RECORDED,
    PROFILE_UPDATED,
    POSITION_ADDED,
    POSITION_UPDATED,
    PAYROLL_UPDATED,
    PROJECT_CREATED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    EMPLOYEE_REMOVED
}
